import React from "react";
import { Sparkles, Bot, Info } from "lucide-react";

interface AiContentBadgeProps {
  label?: string;
  model?: string;
  variant?: "banner" | "inline" | "pill" | "subtle";
  className?: string;
}

/**
 * Standardized Store-Compliant AI Content Label
 * Meets Apple App Store & Google Play Data Safety requirements for AI-generated outputs.
 */
export const AiContentBadge: React.FC<AiContentBadgeProps> = ({
  label = "AI-Generated Analysis & Estimate",
  model = "Gemini 2.5 Flash",
  variant = "pill",
  className = ""
}) => {
  if (variant === "banner") {
    return (
      <div className={`p-3 rounded-xl bg-amber-500/10 border border-amber-500/30 text-amber-800 dark:text-gold flex items-center justify-between gap-3 text-xs font-mono ${className}`}>
        <div className="flex items-center gap-2">
          <Sparkles className="w-4 h-4 text-amber-500 shrink-0 animate-pulse" />
          <span>
            <strong>{label}</strong> • Powered by {model} (SMC Pro AI Engine)
          </span>
        </div>
        <span className="text-[10px] bg-amber-500/20 px-2 py-0.5 rounded-full font-bold uppercase tracking-wider text-amber-900 dark:text-amber-200">
          AI Verified
        </span>
      </div>
    );
  }

  if (variant === "inline") {
    return (
      <span className={`inline-flex items-center gap-1.5 text-[11px] font-mono text-amber-600 dark:text-amber-400 bg-amber-500/10 px-2 py-0.5 rounded-md border border-amber-500/20 ${className}`}>
        <Bot className="w-3 h-3 text-amber-500" />
        <span>{label}</span>
      </span>
    );
  }

  if (variant === "subtle") {
    return (
      <div className={`flex items-center gap-1.5 text-[10px] font-mono text-neutral-400 dark:text-neutral-500 ${className}`}>
        <Info className="w-3 h-3" />
        <span>Output generated by SMC Pro AI ({model}). Verify measurements on-site.</span>
      </div>
    );
  }

  // Default pill
  return (
    <div className={`inline-flex items-center gap-1.5 px-2.5 py-1 rounded-full bg-neutral-900/90 dark:bg-neutral-800 border border-amber-500/40 text-amber-300 text-[10px] font-mono font-bold shadow-xs ${className}`}>
      <Sparkles className="w-3 h-3 text-amber-400 animate-pulse" />
      <span>{label} ({model})</span>
    </div>
  );
};
